# Generated by Django 5.2.3 on 2025-06-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('ingredients', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('interm', 'Intermediate'), ('medi', 'Medium'), ('hard', 'Hard')], default='easy', max_length=12)),
                ('cooking_time', models.IntegerField(help_text='in minutes!')),
            ],
        ),
    ]
