# Generated by Django 5.2.3 on 2025-07-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredient_recipe_description_recipe_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='Please describe your recipe.', max_length=500),
        ),
    ]
